@extends('layouts.frontend.base')

@section('title', 'Construction métallique — Expert en construction et rénovation en Côte d\'Ivoire')
@section('meta_description', 'Découvrez notre projet de construction métallique réalisé par Dibmat & Build : détails, photos et expertise.')
@section('meta_keywords', 'réalisation, projet construction métallique, rénovation, construction, Dibmat & Build')
@section('meta-image', asset('assets/front/images/main-slider/slider2/image3.png'))

@section('content')

<!-- CONTENT START -->
<div class="page-content">
    <!-- INNER PAGE BANNER -->
    <div class="wt-bnr-inr overlay-wraper bg-center" style="background-image:url({{ url('assets/front/images/main-slider/slider2/image3.png') }});">
        <div class="overlay-main site-bg-black opacity-07"></div>
        <div class="container">
            <div class="wt-bnr-inr-entry">
                <div class="banner-title-outer">
                    <div class="banner-title-name">
                        <h2 class="wt-title site-text-primary" style="margin-bottom: 10px; color: #F57C00;">DIBMAT & BUILD</h2>
                        <h2 class="wt-title text-uppercase" style="margin-bottom: 100px;">Decouvrez notre expertise</h2>
                    </div>
                </div>
                <!-- BREADCRUMB ROW -->                            
                        
                <div>
                    <ul class="wt-breadcrumb breadcrumb-style-2">
                        <li><a href="{{ route('home.accueil') }}">Dibmat & Build</a></li>
                        <li>Notre expertise</li>
                    </ul>
                </div>
            
                <!-- BREADCRUMB ROW END -->                        
            </div>
        </div>
    </div>
    <!-- INNER PAGE BANNER END -->         

    <!-- SERVICE DETAIL SECTION START -->
    <div class="section-full p-t120 p-b90 bg-white">
        <div class="section-content">
            <div class="container">
                <div class="row">
                
                    <div class="col-lg-8 col-md-12">
                        <div class="section-content service-full-info">
                            <div class="services-etc m-b30">
                                <div class="text-left">
                                    <h4 class="wt-title m-b20 site-text-primary">CONSTRUCTION METALLIQUE ET DE BÂTIMENT</h4>
                                </div>
                                <p>
                                    L’entreprise générale de bâtiment avec l’intervention de l’ensemble des corps d’états : *Gros- oeuvre (Terrassements, Génie civil, Charpente, Couverture,
                                    Étanchéité,) *Parachèvements (Revêtements murs et sols, Menuiserie,
                                    Peinture,) *Techniques spéciales (Électricité, Sanitaires, ventilation, etc.)
                                    *Aménagements extérieurs (Espaces verts, Pavage,)
                                    - la construction, la rénovation, la réhabilitation, l’achèvement et l’entretien de maisons
                                    familiales, d’immeubles à appartements, de commerces et bureaux, de halls industriels,d’hôpitaux, d’infrastructures sportives et éducatives, etc.
                                    - La construction métallique : entrepôts, hangars, charpentes métalliques,
                                    etc.
                                </p>
                                
                                <!-- <p>After submitting your application, our specialist will come to your home to determine the optimal amount of energy generated by solar panels, based on your electricity consumption. It’s free and doesn’t take more than 40 minutes. Next, our specialist will offer you various types of solar panels and batteries to save the accum- ulated solar energy for the day. After that, you will have time to think and you can order all the necessary equipment directly from us. We also offer discounts on our partners ‘ equipment.</p> 
                                <div class="wt-media m-b30">
                                    <img src="images/services/1.jpg" alt=""> 
                                </div>                                         
                                -->

                                <div class="video-section-three overlay-wraper bg-cover m-b30" style="background-image: url({{ url('assets/front/images/travaux_4.jpg') }}); border-radius: 5px;">
                                    <div class="overlay-main site-bg-black opacity-01" style="border-radius: 5px;"></div>
                                    <a href="https://www.youtube.com/watch?v=c1XNqw2gSbU" class="mfp-video play-now-video">
                                        <i class="icon fa fa-play"></i>
                                        <span class="ripple"></span>
                                    </a>
                                </div>

                                <div class="service-provide m-b30">
                                    <h4 class="wt-title m-b20 text-uppercase site-text-primary">Pourquoi nous confier votre projet de construction métallique</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                                            aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur 
                                            adipisicing elit. 
                                    </p>
                                    <ul class="description-list">
                                        <li><i class="flaticon-checked"></i>Quality Construction Solutions For Industries!</li>
                                        <li><i class="flaticon-checked"></i>Expertise &amp; Innovation from a truly global company</li>
                                        <li><i class="flaticon-checked"></i>Highly Professional Staff, Accurate Testing Processes</li>
                                    </ul>
                                    
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                                        aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Lorem ipsum dolor sit amet, consectetur 
                                            adipisicing elit. 
                                    </p>
                                </div>

                            </div>


                            
                            
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12 rightSidebar">
                        <div class="all_services_list">
                            
                            <div class="all_services m-b30">
                                <ul>
                                    <li><a href="{{ route('home.service_construction') }}" class="active">Construction Métallique</a></li>
                                    <li><a href="{{ route('home.electricite') }}" >Travaux d’électricité et énergie</a></li>
                                    <li><a href="{{ route('home.climatisation') }}">Travaux de climatisation</a></li>
                                    <li><a href="{{ route('home.batiment') }}">Bâtiment</a></li>
                                    
                                </ul>
                            </div>
                        </div>
                    
                    </div>
                </div>                            
            </div>                                 
        </div>
    </div>   

    <div class="section-full p-b90 projects-outer-full  site-bg-white">
        
        <div class="container">
        
            <!-- TITLE START-->
            <div class="section-head center wt-small-separator-outer">
                <div class="wt-small-separator site-text-primary text-uppercase">
                    <div>DES PROJETS DE Constructions métalliques Réalisés</div>
                </div>
                
            </div>
            <!-- TITLE END-->

            <div class="s-section">
                <div class="row">
                    <!-- COLUMNS 1 --> 
                    {{-- <div class="col-lg-4 col-md-6 col-sm-6 m-b30">
                        <div class="service-box-style2">

                            <div class="service-media">
                                <img src="{{ url('assets/front/images/travaux_3.jpg')}}" alt="">
                            </div>
                            
                            <div class="service-content">
                                <div class="service-media-hvr" style="background-image:url({{ url('assets/front/images/travaux_3.jpg') }});"></div>
                                <div class="service-content-data">
                                    <h3 class="service-title-large"><a href="service-detail.html">Racordement Electrique</a></h3>
                                    <p>You can dream, create, design and build the most wonderful place in the world.</p>
                                    <a href="service-detail.html" class="site-buttons btn-hover-animation boxshadow">En savoir plus</a>
                                </div>
                            </div>

                            <div class="service-content2">
                                <h4 class="service-title-large2"><a href="service-detail.html">Racordement Electrique</a></h4>
                                
                            </div>

                        </div>
                    </div> --}}

                    <!-- COLUMNS 2 --> 
                    {{-- <div class="col-lg-4 col-md-6 col-sm-6 m-b30">
                        <div class="service-box-style2">

                            <div class="service-media">
                                <img src="{{ url('assets/front/images/travaux_3.jpg')}}" alt="">
                            </div>
                            
                            <div class="service-content">
                                <div class="service-media-hvr" style="background-image:url({{ url('assets/front/images/travaux_3.jpg') }});"></div>
                                <div class="service-content-data">
                                    <h3 class="service-title-large"><a href="service-detail.html">Racordement Electrique</a></h3>
                                    <p>You can dream, create, design and build the most wonderful place in the world.</p>
                                    <a href="service-detail.html" class="site-buttons btn-hover-animation boxshadow">En savoir plus</a>
                                </div>
                            </div>

                            <div class="service-content2">
                                <h4 class="service-title-large2"><a href="service-detail.html">Racordement Electrique</a></h4>
                                
                            </div>

                        </div>
                    </div> --}}
                    
                    <!-- COLUMNS 3 --> 
                    {{-- <div class="col-lg-4 col-md-6 col-sm-6 m-b30">
                        <div class="service-box-style2">

                            <div class="service-media">
                                <img src="{{ url('assets/front/images/travaux_3.jpg') }}" alt="">
                            </div>
                            
                            <div class="service-content">
                                <div class="service-media-hvr" style="background-image:url({{ url('assets/front/images/travaux_3.jpg') }});"></div>
                                <div class="service-content-data">
                                    <h3 class="service-title-large"><a href="service-detail.html">Racordement Electrique</a></h3>
                                    <p>You can dream, create, design and build the most wonderful place in the world.</p>
                                    <a href="service-detail.html" class="site-buttons btn-hover-animation boxshadow">En savoir plus</a>
                                </div>
                            </div>

                            <div class="service-content2">
                                <h4 class="service-title-large2"><a href="service-detail.html">Racordement Electrique</a></h4>
                                
                            </div>

                        </div>
                    </div>  --}}
                    
                        <!-- COLUMNS 4 --> 

                    @foreach ($projetsRecents as $projetsRecent)
                                        <div class="col-lg-4 col-md-6 col-sm-6 m-b30">
                                        <div class="service-box-style2">
        
                                            <div class="service-media">
                                                <img src="{{ url($projetsRecent->image) }}" alt="">
                                            </div>
                                            
                                            <div class="service-content">
                                                <div class="service-media-hvr" style="background-image:url({{ url($projetsRecent->image) }});"></div>
                                                <div class="service-content-data">
                                                    <h3 class="service-title-large"><a href="{{ route('projets.detail', $projetsRecent->slug) }}">{{ $projetsRecent->name }}</a></h3>
                                                    <p>{{ $projetsRecent->description }}</p>
                                                    <a href="{{ route('projets.detail', $projetsRecent->slug) }}" class="site-buttons btn-hover-animation boxshadow">En savoir plus</a>
                                                </div>
                                            </div>
        
                                            <div class="service-content2">
                                                <h4 class="service-title-large2"><a href="{{ route('projets.detail', $projetsRecent->slug) }}">{{ $projetsRecent->name }}</a></h4>
                                               
                                            </div>
        
                                        </div>
                                    </div>
                                    @endforeach
                    
                </div>
                
            </div>

        </div>      
                
    </div>
    <!-- SERVICE DETAIL SECTION END --> 

    <!-- CLIENT LOGO SECTION START -->

    <div class="section-full site-bg-white p-t50 p-b120 bg-moving"  style="background-color: #fff;">
        
        <!-- TITLE START-->
        <div class="container">
            <!-- TITLE START-->
            <div class="section-head center wt-small-separator-outer">
                <div class="wt-small-separator site-text-primary text-uppercase">
                    <div>des clients plus que satisfaits</div>
                </div>
                <!-- <h2>We provide a variety of construction services</h2> -->
            </div>
            <!-- TITLE END--> 
        </div>
        <!-- TITLE END-->  

        <div class="container home-client3-outer">
            <div class="section-content">
                <div class="home-client-carousel3-wrap">
                    <div class="owl-carousel home-client-carousel3 owl-btn-vertical-center">
                    
                        <div class="item">
                            <div class="ow-client-logo">
                                <div class="client-logo client-logo-media">
                                <a href="about-2.html"><img src="{{ url('assets/front/images/client-logo/images.jpg') }}" alt=""></a></div>
                            </div>
                        </div>
                        
                        <div class="item">
                            <div class="ow-client-logo">
                                <div class="client-logo client-logo-media">
                                <a href="about-2.html"><img src="{{ url('assets/front/images/client-logo/images_dabou.jpeg') }}" alt=""></a></div>
                            </div>
                        </div>
                        
                        <div class="item">
                            <div class="ow-client-logo">
                                <div class="client-logo client-logo-media">
                                <a href="about-2.html"><img src="{{ url('assets/front/images/client-logo/coris logo.png') }}" alt=""></a></div>
                            </div>
                        </div>
                        
                        <div class="item">
                            <div class="ow-client-logo">
                                <div class="client-logo client-logo-media">
                                <a href=""><img src="{{ url('assets/front/images/client-logo/LOGO_APS_H-01.jpg') }}" alt=""></a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- CLIENT LOGO  SECTION End -->  

    <div class="section-full">
        
        <div class="gmap-outline">
            <div class="google-map">
                <div style="width: 100%">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3972.4992867088854!2d-4.0588241!3d5.340477900000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfc1ebcf5c4db451%3A0xcab03beb1052998e!2sGADYS%20INDUSTRIE!5e0!3m2!1sen!2sci!4v1746796179911!5m2!1sen!2sci" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
            
    </div>
     
</div>
<!-- CONTENT END -->

@endsection